import { MODE4_PRELAUNCH_STYLE, type Mode4Style } from '$lib/constants/mode4'

export const MODE4_STYLE_PRELAUNCH: Mode4Style = MODE4_PRELAUNCH_STYLE
export const MODE4_PRELAUNCH_REPLACEMENT_PROMPT = 'You are a helpful assistant.'
export const MODE4_CODEX_MANAGED_INSTRUCTIONS_FILENAME = 'instructions.md'

export const MODE4_CODEX_CR_STYLE_INSTRUCTIONS = `${MODE4_PRELAUNCH_REPLACEMENT_PROMPT}
`

export const MODE4_CLAUDE_CR_STYLE_SYSTEM_PROMPT = MODE4_PRELAUNCH_REPLACEMENT_PROMPT
