import { json } from '@sveltejs/kit'
import type { RequestHandler } from './$types'
import { apiKeyService } from '$lib/services/apiKey.server'
import fs from 'fs/promises'
import path from 'path'
import { env } from '$env/dynamic/private'

const SERVICE_ENV_PATH = path.resolve(process.cwd(), '..', 'batshit-server', 'server', '.env')
const SERVICE_ENV_BACKUP_PATH = `${SERVICE_ENV_PATH}.bak`
const MANAGED_ENV_KEYS = new Set(['BATSHIT_TOKEN', 'BATSHIT_ARTIFACT_COMPLETE_URL'])

function isContainerizedRuntime() {
  return env.BATSHIT_CONTAINERIZED === '1'
}

function isMacAppRuntime() {
  return env.BATSHIT_RUNTIME_OWNER === 'mac-app'
}

function runtimeToken() {
  return (env.BATSHIT_TOKEN || '').trim()
}

function runtimeLabel() {
  if (isMacAppRuntime()) return 'Mac runtime'
  if (isContainerizedRuntime()) return 'Docker Compose environment variables'
  return 'source runtime environment'
}

function parseEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {}
  content.split(/\r?\n/).forEach((line) => {
    if (!line || line.trim().startsWith('#')) return
    const [k, ...rest] = line.split('=')
    if (!k) return
    out[k.trim()] = rest.join('=').trim()
  })
  return out
}

async function readStatus(managed: Record<string, string>) {
  try {
    const content = await fs.readFile(SERVICE_ENV_PATH, 'utf8')
    const parsed = parseEnv(content)
    for (const [k, v] of Object.entries(managed)) {
      if (!parsed[k]) return { status: 'needs-sync', detail: `${k} missing` }
      if (parsed[k] !== v) return { status: 'needs-sync', detail: `${k} differs` }
    }
    return { status: 'synced' }
  } catch (err: any) {
    if (err?.code === 'ENOENT') return { status: 'missing' }
    return { status: 'error', detail: 'Read failed' }
  }
}

async function writeEnv(managed: Record<string, string>) {
  let existing = ''
  try {
    existing = await fs.readFile(SERVICE_ENV_PATH, 'utf8')
  } catch (_) {
    existing = ''
  }

  const lines = existing.split(/\r?\n/)
  const preserved: string[] = []
  const managedKeys = new Set<string>([...MANAGED_ENV_KEYS, ...Object.keys(managed)])

  for (const line of lines) {
    if (!line.trim() || line.trim().startsWith('#')) {
      preserved.push(line)
      continue
    }
    const [k] = line.split('=', 1)
    if (managedKeys.has(k.trim())) continue
    preserved.push(line)
  }

  const header = '# Auto-generated by Batshit Settings → API Keys (managed keys below)'
  const managedBlock = Object.entries(managed)
    .map(([k, v]) => `${k}=${v}`)
    .join('\n')

  const newContent = [header, managedBlock, '', ...preserved].join('\n').trim() + '\n'

  if (existing.trim().length > 0) {
    await fs.writeFile(SERVICE_ENV_BACKUP_PATH, existing, 'utf8')
  }

  await fs.writeFile(SERVICE_ENV_PATH, newContent, 'utf8')
}

function resolveDefaultArtifactCompleteUrl(request: Request): string {
  const origin = new URL(request.url).origin
  return `${origin}/api/artifacts/complete`
}

function resolveRuntimeManagedStatus(request: Request) {
  return {
    status: 'runtime-managed',
    managedByRuntime: true,
    tokenConfigured: Boolean(runtimeToken()),
    artifactCompleteUrl:
      (env.BATSHIT_ARTIFACT_COMPLETE_URL || '').trim() || resolveDefaultArtifactCompleteUrl(request),
    detail: `BATSHIT_TOKEN is managed by ${runtimeLabel()}.`
  }
}

export const GET: RequestHandler = async ({ url, locals, request }) => {
  const userId = locals.user?.id
  if (!userId) return json({ error: 'Unauthorized' }, { status: 401 })

  if (!url.searchParams.get('status')) {
    return json({ ok: true })
  }

  if (isContainerizedRuntime() || isMacAppRuntime()) {
    return json(resolveRuntimeManagedStatus(request))
  }

  const [completeUrl] = await Promise.all([
    apiKeyService.retrieve('batshit_artifact_complete_url', userId)
  ])
  const effectiveToken = runtimeToken()

  if (!effectiveToken) {
    return json({ status: 'needs-sync', detail: 'BATSHIT_TOKEN missing from source runtime environment' })
  }

  const resolvedCompleteUrl = completeUrl?.trim() || resolveDefaultArtifactCompleteUrl(request)

  const managed = {
    BATSHIT_TOKEN: effectiveToken,
    BATSHIT_ARTIFACT_COMPLETE_URL: resolvedCompleteUrl
  }

  const status = await readStatus(managed)
  return json(status)
}

export const POST: RequestHandler = async ({ locals, request }) => {
  const userId = locals.user?.id
  if (!userId) return json({ error: 'Unauthorized' }, { status: 401 })

  if (isContainerizedRuntime() || isMacAppRuntime()) {
    return json({
      success: true,
      ...resolveRuntimeManagedStatus(request)
    })
  }

  const [completeUrl] = await Promise.all([
    apiKeyService.retrieve('batshit_artifact_complete_url', userId)
  ])
  const effectiveToken = runtimeToken()

  if (!effectiveToken) {
    return json({
      error: 'Missing required values',
      missing: {
        batshit_token: !effectiveToken,
        batshit_artifact_complete_url: false
      },
      detail: 'BATSHIT_TOKEN is missing from the source runtime environment.'
    }, { status: 400 })
  }

  const resolvedCompleteUrl = completeUrl?.trim() || resolveDefaultArtifactCompleteUrl(request)

  const managed = {
    BATSHIT_TOKEN: effectiveToken,
    BATSHIT_ARTIFACT_COMPLETE_URL: resolvedCompleteUrl
  }

  try {
    await writeEnv(managed)
    return json({ success: true, path: SERVICE_ENV_PATH, backupPath: SERVICE_ENV_BACKUP_PATH })
  } catch (err) {
    console.error('[service-env] Failed to write .env', err)
    return json({ error: 'Failed to write batshit-server .env' }, { status: 500 })
  }
}

export const DELETE: RequestHandler = async ({ locals }) => {
  const userId = locals.user?.id
  if (!userId) return json({ error: 'Unauthorized' }, { status: 401 })

  if (isContainerizedRuntime() || isMacAppRuntime()) {
    return json({
      success: true,
      managedByRuntime: true,
      detail: `BATSHIT_TOKEN is managed by ${runtimeLabel()}.`
    })
  }

  try {
    let existing = ''
    try {
      existing = await fs.readFile(SERVICE_ENV_PATH, 'utf8')
    } catch (_) {
      return json({ success: true, path: SERVICE_ENV_PATH })
    }

    const managedKeys = MANAGED_ENV_KEYS
    const preserved = existing
      .split(/\r?\n/)
      .filter((line) => {
        if (!line.trim() || line.trim().startsWith('#')) return true
        const [k] = line.split('=', 1)
        return !managedKeys.has(k.trim())
      })

    const newContent = preserved.join('\n').trim() + (preserved.length ? '\n' : '')
    await fs.writeFile(SERVICE_ENV_PATH, newContent, 'utf8')
    return json({ success: true, path: SERVICE_ENV_PATH })
  } catch (err) {
    console.error('[service-env] Failed to delete managed keys', err)
    return json({ error: 'Failed to update batshit-server .env' }, { status: 500 })
  }
}
