export {
  FACIAL_ARTWORK_V6_SCHEMA_VERSION as FACIAL_ARTWORK_SCHEMA_VERSION,
  FACIAL_ARTWORK_V6_STATE_SCHEMA_VERSION as FACIAL_ARTWORK_STATE_SCHEMA_VERSION,
  FACIAL_ARTWORK_V6_ROLE_IDS as FACIAL_ARTWORK_ROLE_IDS,
  FACIAL_ARTWORK_V6_EDITABLE_TRANSFORMS as FACIAL_ARTWORK_EDITABLE_TRANSFORMS,
  collectFacialArtworkUploadsV6 as collectFacialArtworkUploads,
  collectFacialArtworkUploadUrlsV6 as collectFacialArtworkUploadUrls,
  createDefaultFacialArtworkStateV6 as createDefaultFacialArtworkState,
  createFacialArtworkArtworkLayerV6 as createFacialArtworkArtworkLayer,
  parseFacialArtworkDefinitionV6 as parseFacialArtworkDefinition,
  parseFacialArtworkStateV6 as parseFacialArtworkState,
  reconcileFacialArtworkStateV6 as reconcileFacialArtworkState,
  resolveFacialArtworkAssetUrlV6 as resolveFacialArtworkAssetUrl,
  resolveFacialArtworkEyeStateV6 as resolveFacialArtworkEyeState,
  resolveFacialArtworkStateV6 as resolveFacialArtworkState,
  resolveFacialArtworkV6SocketProjectionMode as resolveFacialArtworkSocketProjectionMode,
  resolveFacialArtworkTemplateOrientationV6 as resolveFacialArtworkTemplateOrientation,
  resolveFacialArtworkTemplateVariantV6 as resolveFacialArtworkTemplateVariant,
  type FacialArtworkDefinitionV6 as FacialArtworkDefinition,
  type FacialArtworkStateV6 as FacialArtworkState,
  type FacialArtworkV6ArtworkLayer as FacialArtworkArtworkLayer,
  type FacialArtworkV6Asset as FacialArtworkAsset,
  type FacialArtworkV6EyeState as FacialArtworkEyeState,
  type FacialArtworkV6LongitudeBounds as FacialArtworkLongitudeBounds,
  type FacialArtworkV6LongitudeTransform as FacialArtworkLongitudeTransform,
  type FacialArtworkV6MaskAsset as FacialArtworkMaskAsset,
  type FacialArtworkV6Orientation as FacialArtworkOrientation,
  type FacialArtworkV6PlanarBounds as FacialArtworkPlanarBounds,
  type FacialArtworkV6PlanarTransform as FacialArtworkPlanarTransform,
  type FacialArtworkV6Provenance as FacialArtworkProvenance,
  type FacialArtworkV6ResolvedTemplateVariant as FacialArtworkTemplateVariant,
  type FacialArtworkV6RoleDefinition as FacialArtworkRoleDefinition,
  type FacialArtworkV6RoleId as FacialArtworkRoleId,
  type FacialArtworkV6RoleState as FacialArtworkRoleState,
  type FacialArtworkV6Rgba as FacialArtworkRgba,
  type FacialArtworkV6Rgb as FacialArtworkRgb,
  type FacialArtworkV6RuntimeTarget as FacialArtworkRuntimeTarget,
  type FacialArtworkV6SemanticMapAsset as FacialArtworkSemanticMapAsset,
  type FacialArtworkV6Side as FacialArtworkSide,
  type FacialArtworkV6SocketProjectionMode as FacialArtworkSocketProjectionMode,
  type FacialArtworkV6Template as FacialArtworkTemplate,
  type FacialArtworkV6TemplateBinding as FacialArtworkTemplateBinding,
  type FacialArtworkV6TrustedArtworkEntry as FacialArtworkTrustedArtworkEntry,
  type FacialArtworkV6Upload as FacialArtworkUpload
} from './facialArtworkV6'
