import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = fileURLToPath(new URL('../', import.meta.url))
const iconsDir = path.resolve(projectRoot, 'static/ai-branding')
const generatedDirName = 'ai-branding-generated'
const generatedDir = path.resolve(projectRoot, `static/${generatedDirName}`)
const outputFile = path.resolve(projectRoot, 'src/lib/data/brand-icons.generated.ts')
const brandColorsPath = path.resolve(projectRoot, 'scripts/brand-icon-colors.json')

type BrandColorMap = Record<string, string>

function sanitize(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '')
}

function normalizeHex(value: string) {
  const hex = value.toLowerCase()
  if (hex.length === 4) {
    return `#${hex[1]}${hex[1]}${hex[2]}${hex[2]}${hex[3]}${hex[3]}`
  }
  if (hex.length === 7) return hex
  return hex
}

function isGrayscale(hex: string) {
  const value = hex.slice(1)
  const r = parseInt(value.slice(0, 2), 16)
  const g = parseInt(value.slice(2, 4), 16)
  const b = parseInt(value.slice(4, 6), 16)
  return r === g && g === b
}

function isMonochrome(svg: string) {
  const matches = svg.match(/#[0-9a-fA-F]{3,6}/g) ?? []
  if (!matches.length) return true
  const unique = new Set(matches.map((match) => normalizeHex(match)))
  return !Array.from(unique).some((hex) => !isGrayscale(hex))
}

function detectTheme(slug: string) {
  if (slug.endsWith('-dark')) return { theme: 'dark' as const, base: slug.slice(0, -5) }
  if (slug.endsWith('-light')) return { theme: 'light' as const, base: slug.slice(0, -6) }
  return { theme: null, base: slug }
}

function detectVariant(slug: string) {
  if (slug.endsWith('-color')) return { variant: 'color' as const, base: slug.slice(0, -6) }
  if (slug.endsWith('-mono')) return { variant: 'mono' as const, base: slug.slice(0, -5) }
  if (slug.endsWith('-brand')) return { variant: 'brand' as const, base: slug.slice(0, -6) }
  return { variant: 'default' as const, base: slug }
}

async function run() {
  const entries = await fs.readdir(iconsDir)
  const iconFiles = entries
    .filter((file) => file.endsWith('.svg') || file.endsWith('.png'))
    .sort((a, b) => a.localeCompare(b))
  const brandColorMap: BrandColorMap = JSON.parse(await fs.readFile(brandColorsPath, 'utf8'))

  await fs.rm(generatedDir, { recursive: true, force: true })
  await fs.mkdir(generatedDir, { recursive: true })

  const mapEntries: string[] = []
  const metaEntries: string[] = []

  for (const file of iconFiles) {
    const isSvg = file.endsWith('.svg')
    const slug = file.replace(/\.(svg|png)$/, '')
    const { theme, base: slugWithoutTheme } = detectTheme(slug)
    const { variant, base: canonicalBase } = detectVariant(slugWithoutTheme)
    const canonicalSlug = sanitize(canonicalBase)

    const filePath = path.resolve(iconsDir, file)
    const content = isSvg ? await fs.readFile(filePath, 'utf8') : ''
    const usesCurrentColor = isSvg && content.includes('currentColor')
    const brandColor = brandColorMap[canonicalSlug] ? normalizeHex(brandColorMap[canonicalSlug]) : null

    let mapPath = `/ai-branding/${file}`
    if (usesCurrentColor && brandColor) {
      const tintedContent = content.replace(/currentColor/gi, brandColor)
      const tintedFileName = `${slug}.svg`
      await fs.writeFile(path.resolve(generatedDir, tintedFileName), tintedContent, 'utf8')
      mapPath = `/${generatedDirName}/${tintedFileName}`
    }
    mapEntries.push(`  '${slug}': '${mapPath}',`)

    const explicitMono = variant === 'mono'
    const monochrome = isSvg && (explicitMono || (!usesCurrentColor && isMonochrome(content)))
    metaEntries.push(
      `  '${slug}': { monochrome: ${monochrome}, variant: '${variant}', theme: ${
        theme ? `'${theme}'` : null
      }, brandColor: ${brandColor ? `'${brandColor}'` : null}, usesCurrentColor: ${usesCurrentColor} },`
    )
  }

  const content = `// Auto-generated by scripts/generate-brand-icons.ts. Do not edit manually.\nexport const BRAND_ICON_MAP = {\n${mapEntries.join(
    '\n'
  )}\n} as const;\n\nexport const BRAND_ICON_META = {\n${metaEntries.join(
    '\n'
  )}\n} as const;\n\nexport type BrandIconSlug = keyof typeof BRAND_ICON_MAP;\n`

  await fs.writeFile(outputFile, content, 'utf8')
  console.log(`Updated brand icon map with ${iconFiles.length} entries.`)
}

run().catch((error) => {
  console.error('Failed to generate brand icon map:', error)
  process.exit(1)
})
