<script lang="ts">
  import {
    AlertCircle,
    Bug,
    CheckCircle2,
    Download,
    Eye,
    FileText,
    Loader2,
    ShieldCheck
  } from '@lucide/svelte'
  import * as Label from '$lib/components/ui/label'
  import { Badge } from '$lib/components/ui/badge'
  import { Button } from '$lib/components/ui/button'
  import SettingsAccordionCard from '$lib/components/settings/SettingsAccordionCard.svelte'
  import SettingsInfoMenu from '$lib/components/settings/SettingsInfoMenu.svelte'
  import {
    formatBackupBytes,
    formatBackupDate,
    type DiagnosticsPreviewSummary
  } from './adminSettingsTypes'

  interface Props {
    previewBusy: boolean
    exportBusy: boolean
    preview: DiagnosticsPreviewSummary | null
    error: string | null
    open?: boolean
    openNonce?: number
    onPreview: () => void
    onExport: () => void
  }

  let {
    previewBusy,
    exportBusy,
    preview,
    error,
    open = false,
    openNonce = 0,
    onPreview,
    onExport
  }: Props = $props()
</script>

{#key openNonce}
<SettingsAccordionCard
  name="admin-settings-cards"
  title="Diagnostics"
  icon={Bug}
  {open}
  contentClass="space-y-4"
>
  {#snippet info()}
    <SettingsInfoMenu ariaLabel="About Diagnostics" contentClass="w-80">
      <p>
        Creates a support zip for bug reports. Batshit previews the bundle first and excludes chats,
        prompts, uploads, project files, backups, API keys, tokens, cookies, and raw Redis data.
      </p>
    </SettingsInfoMenu>
  {/snippet}

  <div class="space-y-4">
    <div class="batshit-settings-form-stack">
      <div class="batshit-settings-form-row">
        <div class="batshit-settings-form-copy">
          <div class="batshit-settings-form-label-line">
            <Label.Root class="batshit-settings-form-label">Export Diagnostics</Label.Root>
            <SettingsInfoMenu ariaLabel="About Export Diagnostics" contentClass="w-80">
              <p>
                The preview and zip are generated by the same redaction path. Log files are capped to
                recent tails, and known secret patterns are replaced before export.
              </p>
            </SettingsInfoMenu>
          </div>
        </div>
        <div class="batshit-settings-form-control">
          <div class="batshit-backup-action-row">
            <Button type="button" size="sm" onclick={onPreview} disabled={previewBusy || exportBusy}>
              {#if previewBusy}
                <Loader2 class="animate-spin" aria-hidden="true" />
                Preparing
              {:else}
                <Eye aria-hidden="true" />
                {preview ? 'Refresh Preview' : 'Export Diagnostics'}
              {/if}
            </Button>
          </div>
        </div>
      </div>
    </div>

    {#if preview}
      <div class="rounded-md border border-border/80 bg-muted/30 p-3">
        <div class="flex flex-wrap items-center gap-2">
          <Badge variant="outline">Created {formatBackupDate(preview.createdAt)}</Badge>
          <Badge variant="outline">Batshit {preview.app.version}</Badge>
          <Badge variant="outline">{preview.runtime.label}</Badge>
          <Badge variant="outline">
            {preview.contents.logFiles.length} logs / {formatBackupBytes(preview.contents.totalLogBytes)}
          </Badge>
          <Badge variant={preview.health.ok ? 'outline' : 'destructive'}>
            {preview.health.ok ? 'Health OK' : 'Health Warning'}
          </Badge>
        </div>

        <div class="mt-3 grid gap-3 lg:grid-cols-2">
          <div class="rounded border border-border/70 bg-background/60 p-3">
            <div class="mb-2 flex items-center gap-2">
              <FileText class="h-4 w-4 text-muted-foreground" aria-hidden="true" />
              <span class="batshit-settings-form-label">Included</span>
            </div>
            <div class="space-y-2">
              {#each preview.contents.included as item}
                <div>
                  <div class="text-sm font-medium text-foreground">{item.label}</div>
                  <div class="text-xs text-muted-foreground">{item.path}</div>
                </div>
              {/each}
            </div>
          </div>

          <div class="rounded border border-border/70 bg-background/60 p-3">
            <div class="mb-2 flex items-center gap-2">
              <ShieldCheck class="h-4 w-4 text-emerald-500" aria-hidden="true" />
              <span class="batshit-settings-form-label">Not Included</span>
            </div>
            <div class="space-y-1.5">
              {#each preview.safety.notIncluded as item}
                <div class="flex gap-2 text-sm text-muted-foreground">
                  <CheckCircle2 class="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" aria-hidden="true" />
                  <span>{item}</span>
                </div>
              {/each}
            </div>
          </div>
        </div>

        <div class="mt-3 rounded border border-border/70 bg-background/60 p-3">
          <div class="mb-2 flex items-center gap-2">
            <ShieldCheck class="h-4 w-4 text-muted-foreground" aria-hidden="true" />
            <span class="batshit-settings-form-label">Redaction</span>
          </div>
          <div class="flex flex-wrap gap-2">
            {#each preview.safety.redactionPatterns as pattern}
              <Badge variant="outline">{pattern}</Badge>
            {/each}
          </div>
        </div>

        {#if preview.contents.logFiles.length > 0}
          <div class="mt-3 space-y-2">
            <div class="batshit-settings-form-label">Log Preview</div>
            {#each preview.contents.logFiles as log}
              <details class="rounded border border-border/70 bg-background/60 p-3">
                <summary class="cursor-pointer text-sm font-medium text-foreground">
                  {log.entryName}
                  <span class="text-xs font-normal text-muted-foreground">
                    ({formatBackupBytes(log.includedBytes)}{log.truncated ? ', tail only' : ''})
                  </span>
                </summary>
                <div class="mt-2 text-xs text-muted-foreground">
                  Source: {log.source}
                </div>
                {#if log.sample}
                  <pre class="mt-2 max-h-44 overflow-auto rounded border border-border/60 bg-muted/40 p-2 text-xs text-muted-foreground whitespace-pre-wrap">{log.sample}</pre>
                {:else}
                  <div class="mt-2 text-xs text-muted-foreground">No text preview available.</div>
                {/if}
              </details>
            {/each}
          </div>
        {/if}

        {#if preview.safety.warnings.length > 0 || preview.health.errors.length > 0}
          <div class="mt-3 space-y-2">
            {#each [...preview.safety.warnings, ...preview.health.errors] as warning}
              <div class="flex gap-2 text-sm text-muted-foreground">
                <AlertCircle class="mt-0.5 h-4 w-4 shrink-0 text-amber-500" aria-hidden="true" />
                <span>{warning}</span>
              </div>
            {/each}
          </div>
        {/if}

        <div class="mt-3 flex flex-wrap items-center gap-2">
          <Button type="button" size="sm" onclick={onExport} disabled={exportBusy || previewBusy}>
            {#if exportBusy}
              <Loader2 class="animate-spin" aria-hidden="true" />
              Exporting
            {:else}
              <Download aria-hidden="true" />
              Download Diagnostics Zip
            {/if}
          </Button>
          <span class="text-xs text-muted-foreground">{preview.filename}</span>
        </div>
      </div>
    {/if}

    {#if error}
      <div class="flex gap-2 rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
        <AlertCircle class="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
        <span>{error}</span>
      </div>
    {/if}
  </div>
</SettingsAccordionCard>
{/key}
